### PR TITLE
Improve use fetch hook

### PR DESCRIPTION
**Pull request by fekete965**
This PR is trying to address the following issue:
https://github.com/vatsalsinghkv/easy-fix/issues/43

Changes implemented so far:

- A new hook called `useAsync` has been added (with type narrowing)
- `zod` schema library has been added to the project
- `HttpGateway` has been added (with type narrowing based on the schema)
- `use-fetch` hook and related tests have been removed

Please note, that testing is not included.
I am planning to do it in another PR as work is very busy at the moment so if this one is adequate enough, it can be merged, but it is totally up to you @vatsalsinghkv

### CODE REVIEW

**Comment by fekete965** [comment]
@vatsalsinghkv let me know what you think.

**Comment by fekete965** [comment]
> @fekete965 this is an amazing work, can you explain what's HTTPGateway and how does it help i don't know much about it. Sorry for the delay

Yes, I try to explain the pattern being used.

The main idea of an API gateway is to have a common interface for a certain service. In our case I called in `HttpGateway` as it performs `HTTP` requests. Now we have an interface called `HttpGatewayBase` that defines the field and methods that need to be implemented on a `HttpGateway` class. Now why is it good for us? If we have a common API being use in the codebase we can easily swap this instance with another service. In our case the best example probably is the following:
1. We have implemented `HttpGateway` using native `fetch`.
2. We could implement another `HttpGateway` using a library like `axios`
3. We can easily swap out the entire instance without the need to change anything else in our codebase but the singleton instance.

Now this method is usually being used with a `dependency injections` and an `IOC` (Inversion of Control) Container where the container can do this swap for us based on certain conditions.

Another example for this would be the following:
1. We implement a `LocalStorageGatwewayBase` that will define our API to persist data on devices
2. Now we can implement multiple of these instances: 1. Using localstorage 2. Using IndexDB 3. Using a library if needed
3. Now if we would use `react-native` we wouldn't have access to `localstorage` since it lives on the `WebAPI`, but we can have access to `asyncStorage`.
4. This would allow us to share more common code in both the FE and the Mobile app since we can easily use the correct instance based on the device

Now let's talk about the `HttpGateway` and what it does.
It is really just a wrapper around the native `fetch` but with type safety. The class is using `zod` to infer the data type coming back from a server. This makes the application more secure as we would validate the incoming data.

We have also used `method overrides` which help TS to determine the correct return type eg.: If you don't pass a schema into the method, the expected result will be `void`

I think these are the main points of the class, the rest aren't anything "fancy" or interesting. I `omitted` a few values from the `fetch` arguments so people won't try to override those values.

**Comment by fekete965** [comment]
@vatsalsinghkv I hope I managed to explain my idea well 😅 Please let me know if you have any more questions or you would like to see more examples.

I have fixed some issue with data validators. To make the code less "error-prone" I have removed the unused fields from the schemas as the GH docs are poorly made and it would take ages trying to figure out the correct shape of the models.

I also made a tiny mistake by not fetching the data when the URL changes so that has also been fixed.

**Comment by vatsalsinghkv** [comment]
@fekete965 Can you check the deployed preview, whenever we visit the website or refresh we first se the error page for a moment of time before loader shows up, can you check that?

**Comment by fekete965** [comment]
> @fekete965 Can you check the deployed preview, whenever we visit the website or refresh we first se the error page for a moment of time before loader shows up, can you check that?

@vatsalsinghkv I am checking it now.

**Comment by fekete965** [comment]
@vatsalsinghkv it should be fixed no 🤞

**Pull request merged**
