### PR TITLE
feat: Added Scroll-to-top button

### PR DESCRIPTION
**Pull request by parthksingh1**
Added Scroll to top Button which will 
Enhanced User Experience: Users don't need to manually scroll upwards, which can be tedious on very long pages.
Improved Navigation: Provides an easy and quick way to access the top menu or any other content located at the top.
Adaptive Design: Can be designed to appear only after the user has scrolled down a specific amount, ensuring that it doesn't interfere with the initial page view.

Video

https://github.com/vatsalsinghkv/easy-fix/assets/128512586/70b698f2-5c16-4784-9995-009a46bcf035

### CODE REVIEW

**Comment by parthksingh1** [comment]
Please hold off on merging my pull request. I've encountered some issues while creating it. I'll make the necessary changes and notify you once it's ready for review.

**Comment by vatsalsinghkv** [comment]
@parthksingh1 it's amazing but you'd need to make PR from 1st of Oct to get it count as a contribution under Hacktoberfest

**Comment by vatsalsinghkv** [comment]
Hey @parthksingh1 can you pull changes and resolve the merge issues?

**Comment by parthksingh1** [comment]
Okay 👍🏻

**Comment by vatsalsinghkv** [comment]
@parthksingh1 sorry for the delay, bro can you resolve the merge issues and ping me so I can merge this PR

**Comment by parthksingh1** [comment]
@vatsalsinghkv hey can you what's going on i resolved the merge conflict still it is showing and when coming to solve it on github it is showing this 
Screenshot (66)

**Comment by parthksingh1** [comment]
@vatsalsinghkv please review it

**Comment by vatsalsinghkv** [comment]
@parthksingh1 pull the changes?

**Comment by fekete965** [comment]
@parthksingh1, I have a couple of suggestions:

- I think you should be using IntersectionObserver instead of scroll and a fixed height as the page can grow or shrink and just setting the threshold to an arbitrary value can cause some problems later on.
- Tailwind is also being used in the project hence, I would recommend using tailwind instead of the current styling solution.
- @vatsalsinghkv also pointed out to me that the following library is being used: `lucide.dev`
I think it would be nice to use the icon from this package instead of the current arrow.

**Pull request closed without merging**
