### PR TITLE
Improve url provider

### PR DESCRIPTION
**Pull request by fekete965**
The PR was planned to be a small one with a few changes but in the meantime, a lot of code got merged which affected this PR.

This PR covers the following issue: 

This PR includes the following: https://github.com/vatsalsinghkv/easy-fix/issues/35

- A new `models folder` has been introduced
- New `UrlProvider` has been created using TS
- Old `UseUrlProvider` has been removed
- A util function called `composeUrl` has been added and used
- A more meaningful sorting icon has been added and the UI has been updated to indicate the sorting clearly
- Minor `accessibility` and `semantic` improvements have been implemented
- Missing tests have been added and broken tests were fixed

### CODE REVIEW

**Comment by fekete965** [comment]
@vatsalsinghkv there it is. Some of the components can be nicely composed together in a cleaner way but that would be part of another PR which addresses another issue.

**Review by vatsalsinghkv — APPROVED** [review]
This is the coolest contribution in the project, loved it ❤️

**Comment by vatsalsinghkv** [comment]
@fekete965 Can you check there's been some UI issue in the language select buttons, UI doesn't look the same as it should when we unselect them

**Comment by vatsalsinghkv** [comment]
@fekete965 You've used Icons as SVG, what do you think about this icon library: https://lucide.dev/icons/

**Comment by fekete965** [comment]
> @fekete965 Can you check there's been some UI issue in the language select buttons, UI doesn't look the same as it should when we unselect them

Oh shoot. I think I know the problem. Sorry about that!

**Comment by fekete965** [comment]
@vatsalsinghkv, the issue with the language filters is addressed, I also used `lucide` icons instead of the current ones and added some additional tests to confirm we are using the correct icons.

**Comment by fekete965** [comment]
@vatsalsinghkv I am happy to share this with you guys. :) Could you share the discord link, please?

**Pull request merged**
