### PR TITLE
Feature/migrate containers to TS

### PR DESCRIPTION
**Pull request by fekete965**
The following changes have been implemented:

- The following files have been migrated to TS: `containers/Filter`, `containers/Footer`, `containers/Header`, `containers/Issues`, `containers/index`
- `Select` component now takes in an `onChange`. This was necessary to ensure we still have type safety in the `Filter` component as we cannot safely assume what element triggered the `onChange` within the `form` if that handler is attached to the form itself instead of the element. A simple test covers this change.
- Added missing imports to certain test files
- Failing pagination tests were fixed and tweaked pagination logic as it was throwing some errors

### CODE REVIEW

**Comment by vatsalsinghkv** [comment]
@fekete965 nice work mate ❤️. Can you pull the latest changes and fix the merge conflicts in `Header.tsx`

**Comment by fekete965** [comment]
@vatsalsinghkv I've just rebased and pushed the PR.

**Comment by vatsalsinghkv** [comment]
@fekete965 it still shows the conflicts in header, just pull the latest changes, sorry for getting back late

**Comment by fekete965** [comment]
There was something else merged in the meantime by the look of it 🤔

**Comment by fekete965** [comment]
Pulling the latest code and rebasing the PR in a minute.

**Comment by fekete965** [comment]
Rebased and pushed.

**Pull request merged**
