### PR TITLE
Add Label Search

### PR DESCRIPTION
**Pull request by newtoallofthis123**
This commit modifies the reducers to use label search as well. 

It works well in most cases, however, there are two major issues I need help with.

1. The Reducers send more requests for some reason
2. The application _crashes_ when it github returns an error

I am putting this pr in review. Any and all help is appreciated. I am not that good with `tsx`, but I tried my best. @vatsalsinghkv can you please get the help this pr needs?

### CODE REVIEW

**Comment by fekete965** [comment]
@newtoallofthis123 would you be able to run prettier on the codebase, please?

**Comment by newtoallofthis123** [comment]
Sure!

**Comment by fekete965** [comment]
> Sure!

I just noticed that some mult-line imports changed into a single line and I am not sure if there is something with the Prettier config as on my side locally it broke it into multiple lines 🤔
Thank you for checking this for me :)

**Comment by newtoallofthis123** [comment]
There seems to be some sort of a problem....I was able to pin it to the state management....will look into it...any help appreciated :)

**Comment by fekete965** [comment]
@vatsalsinghkv @newtoallofthis123 there is an error in the console:
`Cannot read properties of undefined (reading 'join')`.

I think we try to use `.join` on an optional value. It could be fixed with the `optional chaining (?.join)`

**Comment by fekete965** [comment]
I can take a look at the issue later on if still needed.

**Comment by vatsalsinghkv** [comment]
@newtoallofthis123 Can u pull the changes and resolve conflicts

**Comment by newtoallofthis123** [comment]
Sure! Will do

**Comment by vatsalsinghkv** [comment]
@newtoallofthis123 sorry for reviewing it late, I finally able to run it locally, you've added a text search bar for search by label, but we wanted to have pre-defined buttons for label, for example 
Screenshot 2023-10-14 at 9 49 21 PM

**Pull request closed without merging**
