### PR TITLE
feat: sort by asc/desc order

### PR DESCRIPTION
**Pull request by premtw**
- Eanbled sort by order
image

### CODE REVIEW

**Comment by vatsalsinghkv** [comment]
@premtw I am not able to click the button, only I am able to click text and icon, can you fix it, like the whole button should be clickable (except for icons), can you fix it?

Screenshot 2023-10-08 at 10 32 42 PM

**Comment by premtw** [comment]
@vatsalsinghkv Thanks for spoting out. Pushed an another commt with the changes.

**Comment by vatsalsinghkv** [comment]
@premtw can you fix the merge issues by rebasing?

**Comment by premtw** [comment]
@vatsalsinghkv Updated with upstream main and resolved all the conflicts

**Pull request merged**
