### PR TITLE
footer is updated with social links

### PR DESCRIPTION
**Pull request by hardikjumnani**
#12 I have updated the footer with social links (clickable icons matching with the theme)

### CODE REVIEW

**Comment by hardikjumnani** [comment]
@vatsalsinghkv okay

**Comment by hardikjumnani** [comment]
@vatsalsinghkv made the following required changes

**Comment by hardikjumnani** [comment]
@vatsalsinghkv please check the changes

**Comment by vatsalsinghkv** [comment]
@hardikjumnani  nice work man

**Pull request merged**
